name: Build Code

on:
  pull_request:
    branches: [ "dev" ]
    types: [opened, synchronize, reopened]

jobs:
  build-test-sonar:
    runs-on: windows-latest

    env:
      DOTNET_VERSION: 8.0.x

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu' # Alternative distribution options are available.

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Restore NuGet Packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-dotnet-${{ env.DOTNET_VERSION }}-nuget
          restore-keys: |
            ${{ runner.os }}-dotnet-${{ env.DOTNET_VERSION }}-

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Cache Aspire Workload
        uses: actions/cache@v3
        with:
          path: ~/.dotnet/workloads
          key: ${{ runner.os }}-dotnet-${{ env.DOTNET_VERSION }}-aspire
          restore-keys: |
            ${{ runner.os }}-dotnet-${{ env.DOTNET_VERSION }}-aspire

      - name: Install .NET Aspire Workload
        run: dotnet workload install aspire

      - name: Save NuGet Packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-dotnet-${{ env.DOTNET_VERSION }}-nuget

      - name: Restore dependencies
        run: dotnet restore

      - name: Build Solution
        run: dotnet build --no-restore --configuration Release

      - name: Run Unit Tests
        run: dotnet test --no-build --configuration Release --logger trx --results-directory "TestResults"

      - name: Cache SonarQube Cloud packages
        uses: actions/cache@v4
        with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache SonarQube Cloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v4
        with:
          path: .\.sonar\scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner

      - name: Install SonarQube Cloud scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          New-Item -Path .\.sonar\scanner -ItemType Directory
          dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner

      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: powershell
        run: |
          .\.sonar\scanner\dotnet-sonarscanner begin /k:"19nguyenvantu94_MultiAppServerRender" /o:"19nguyenvantu94" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
          dotnet build
          .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"

      - name: Update GitHub Status
        uses: actions/github-script@v6
        with:
          script: |
            console.log(context);
            const checkRun = context.payload.check_run;
            if (checkRun && checkRun.conclusion) {
              const status = checkRun.conclusion === 'success' ? 'success' : 'failure';
              await github.repos.createCommitStatus({
                ...context.repo,
                sha: context.sha,
                state: status,
                context: 'CI Pipeline',
                description: status === 'success' ? 'All checks passed' : 'Some checks failed',
                target_url: checkRun.html_url
              });
            } else {
              console.error("The 'check_run' object or 'conclusion' property is undefined.");
            }