---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhooksclient
  labels:
    app: webhooksclient
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: webhooksclient
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: webhooksclient
    spec:
      containers:
      - name: webhooksclient
        image: nguyenvantu/webhooksclient:b067808703058475820f03695b31bdf22f62a8b59da21fd48c92daaf4253b4fd
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        envFrom:
        - configMapRef:
            name: webhooksclient-env
      terminationGracePeriodSeconds: 180